/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Examen;

import Vista.*;

/**
 *
 * @author USER
 */
public class TestAvanzado1 extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public TestAvanzado1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpbProgreso = new javax.swing.JProgressBar();
        btnRegresar = new javax.swing.JButton();
        btnContinuar = new javax.swing.JButton();
        txtPregunta2 = new javax.swing.JTextField();
        txtPregunta1 = new javax.swing.JTextField();
        txtPregunta3 = new javax.swing.JTextField();
        txtPregunta4 = new javax.swing.JTextField();
        txtPregunta6 = new javax.swing.JTextField();
        txtPregunta5 = new javax.swing.JTextField();
        lblQuechua = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpbProgreso.setBackground(new java.awt.Color(175, 175, 175));
        jpbProgreso.setForeground(new java.awt.Color(255, 79, 79));
        jpbProgreso.setBorder(null);
        jPanel1.add(jpbProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 590, 30));

        btnRegresar.setToolTipText("");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 220, 40));

        btnContinuar.setToolTipText("");
        btnContinuar.setContentAreaFilled(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 680, 350, 60));

        txtPregunta2.setBackground(new java.awt.Color(234, 234, 234));
        txtPregunta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPregunta2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPregunta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 310, 60));

        txtPregunta1.setBackground(new java.awt.Color(234, 234, 234));
        txtPregunta1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPregunta1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPregunta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 300, 60));

        txtPregunta3.setBackground(new java.awt.Color(234, 234, 234));
        txtPregunta3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPregunta3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPregunta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 300, 60));

        txtPregunta4.setBackground(new java.awt.Color(234, 234, 234));
        txtPregunta4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPregunta4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPregunta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 310, 60));

        txtPregunta6.setBackground(new java.awt.Color(234, 234, 234));
        txtPregunta6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPregunta6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPregunta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 310, 60));

        txtPregunta5.setBackground(new java.awt.Color(234, 234, 234));
        txtPregunta5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPregunta5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtPregunta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 300, 60));

        lblQuechua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/TestAvanzado1.jpg"))); // NOI18N
        jPanel1.add(lblQuechua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed

    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestAvanzado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestAvanzado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestAvanzado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestAvanzado1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestAvanzado1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnContinuar;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JProgressBar jpbProgreso;
    public javax.swing.JLabel lblQuechua;
    public javax.swing.JTextField txtPregunta1;
    public javax.swing.JTextField txtPregunta2;
    public javax.swing.JTextField txtPregunta3;
    public javax.swing.JTextField txtPregunta4;
    public javax.swing.JTextField txtPregunta5;
    public javax.swing.JTextField txtPregunta6;
    // End of variables declaration//GEN-END:variables
}
