/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony
 */
public class Lecciones_Principiante extends javax.swing.JFrame {

    /**
     * Creates new form Seleccion_Nivel
     */
    public Lecciones_Principiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnColores = new javax.swing.JButton();
        btnSemana = new javax.swing.JButton();
        btnSaludos = new javax.swing.JButton();
        btnAnimales = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1040, 660));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/I_colores.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 120, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/I_condor.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 130, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/I_Calendario.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/I_Conversacion.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, 100));

        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B_Regresar.png"))); // NOI18N
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnColores.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnColores.setForeground(new java.awt.Color(255, 255, 255));
        btnColores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B_colores.png"))); // NOI18N
        btnColores.setBorderPainted(false);
        btnColores.setContentAreaFilled(false);
        btnColores.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnColores.setIconTextGap(10);
        btnColores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnColoresMouseClicked(evt);
            }
        });
        jPanel1.add(btnColores, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 200, 120));

        btnSemana.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnSemana.setForeground(new java.awt.Color(255, 255, 255));
        btnSemana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B_Dias.png"))); // NOI18N
        btnSemana.setBorderPainted(false);
        btnSemana.setContentAreaFilled(false);
        btnSemana.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSemana.setIconTextGap(10);
        btnSemana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSemanaMouseClicked(evt);
            }
        });
        jPanel1.add(btnSemana, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 200, 120));

        btnSaludos.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnSaludos.setForeground(new java.awt.Color(255, 255, 255));
        btnSaludos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B_Saludos.png"))); // NOI18N
        btnSaludos.setBorderPainted(false);
        btnSaludos.setContentAreaFilled(false);
        btnSaludos.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnSaludos.setIconTextGap(10);
        btnSaludos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaludosMouseClicked(evt);
            }
        });
        jPanel1.add(btnSaludos, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 110, 200, 120));

        btnAnimales.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btnAnimales.setForeground(new java.awt.Color(255, 255, 255));
        btnAnimales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/B_Animales.png"))); // NOI18N
        btnAnimales.setBorderPainted(false);
        btnAnimales.setContentAreaFilled(false);
        btnAnimales.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnAnimales.setIconTextGap(10);
        btnAnimales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnimalesMouseClicked(evt);
            }
        });
        jPanel1.add(btnAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 180, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/P_Elec_principiante.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 381));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSemanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSemanaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSemanaMouseClicked

    private void btnColoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnColoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnColoresMouseClicked

    private void btnSaludosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaludosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaludosMouseClicked

    private void btnAnimalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnimalesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnimalesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecciones_Principiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecciones_Principiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecciones_Principiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecciones_Principiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecciones_Principiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAnimales;
    public javax.swing.JButton btnColores;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnSaludos;
    public javax.swing.JButton btnSemana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
