/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author USER
 */
public class Lecciones_Intermedio extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarPrincipiante
     */
    public Lecciones_Intermedio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConjugacion = new javax.swing.JButton();
        btnOraciones = new javax.swing.JButton();
        btnDeseo = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnConjugacion.setFont(new java.awt.Font("Tahoma", 1, 9)); // NOI18N
        btnConjugacion.setForeground(new java.awt.Color(255, 255, 255));
        btnConjugacion.setBorder(null);
        btnConjugacion.setBorderPainted(false);
        btnConjugacion.setContentAreaFilled(false);
        btnConjugacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConjugacionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConjugacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 350, 170));

        btnOraciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnOraciones.setForeground(new java.awt.Color(255, 255, 255));
        btnOraciones.setBorder(null);
        btnOraciones.setBorderPainted(false);
        btnOraciones.setContentAreaFilled(false);
        btnOraciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOracionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnOraciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 340, 160));

        btnDeseo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDeseo.setForeground(new java.awt.Color(255, 255, 255));
        btnDeseo.setBorder(null);
        btnDeseo.setBorderPainted(false);
        btnDeseo.setContentAreaFilled(false);
        btnDeseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeseoActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeseo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 240, 150));

        btnRegresar.setFont(new java.awt.Font("Sitka Text", 1, 20)); // NOI18N
        btnRegresar.setBorder(null);
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LeccionesIntermedio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConjugacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConjugacionActionPerformed
  
    }//GEN-LAST:event_btnConjugacionActionPerformed

    private void btnDeseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeseoActionPerformed

    }//GEN-LAST:event_btnDeseoActionPerformed

    private void btnOracionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOracionesActionPerformed
 
    }//GEN-LAST:event_btnOracionesActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecciones_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecciones_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecciones_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecciones_Intermedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecciones_Intermedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnConjugacion;
    public javax.swing.JButton btnDeseo;
    public javax.swing.JButton btnOraciones;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
