
package Vista;

public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnChatbot = new javax.swing.JButton();
        btnLogros = new javax.swing.JButton();
        btnTablaPuntajes = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        btnRecursos = new javax.swing.JButton();
        btnGlosario = new javax.swing.JButton();
        btnEliminarCuenta = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnPracticar = new javax.swing.JButton();
        btnTraducir = new javax.swing.JButton();
        lblESP = new javax.swing.JLabel();
        lblQuechua = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnChatbot.setToolTipText("");
        btnChatbot.setBorderPainted(false);
        btnChatbot.setContentAreaFilled(false);
        jPanel1.add(btnChatbot, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 620, 100, 90));

        btnLogros.setToolTipText("");
        btnLogros.setBorderPainted(false);
        btnLogros.setContentAreaFilled(false);
        jPanel1.add(btnLogros, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 320, 70));

        btnTablaPuntajes.setToolTipText("");
        btnTablaPuntajes.setBorderPainted(false);
        btnTablaPuntajes.setContentAreaFilled(false);
        jPanel1.add(btnTablaPuntajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 320, 70));

        btnTest.setToolTipText("");
        btnTest.setBorderPainted(false);
        btnTest.setContentAreaFilled(false);
        jPanel1.add(btnTest, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 320, 70));

        btnRecursos.setToolTipText("");
        btnRecursos.setBorderPainted(false);
        btnRecursos.setContentAreaFilled(false);
        jPanel1.add(btnRecursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 320, 70));

        btnGlosario.setToolTipText("");
        btnGlosario.setBorderPainted(false);
        btnGlosario.setContentAreaFilled(false);
        jPanel1.add(btnGlosario, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 600, 320, 60));

        btnEliminarCuenta.setToolTipText("");
        btnEliminarCuenta.setBorderPainted(false);
        btnEliminarCuenta.setContentAreaFilled(false);
        jPanel1.add(btnEliminarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, 170, 80));

        btnCerrarSesion.setToolTipText("");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 220, 40));

        btnPracticar.setToolTipText("");
        btnPracticar.setBorderPainted(false);
        btnPracticar.setContentAreaFilled(false);
        jPanel1.add(btnPracticar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 320, 70));

        btnTraducir.setToolTipText("");
        btnTraducir.setBorderPainted(false);
        btnTraducir.setContentAreaFilled(false);
        jPanel1.add(btnTraducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 80));

        lblESP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UIMenuESP.jpg"))); // NOI18N
        jPanel1.add(lblESP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        lblQuechua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UIMenuQUECHUA.jpg"))); // NOI18N
        jPanel1.add(lblQuechua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JButton btnChatbot;
    public javax.swing.JButton btnEliminarCuenta;
    public javax.swing.JButton btnGlosario;
    public javax.swing.JButton btnLogros;
    public javax.swing.JButton btnPracticar;
    public javax.swing.JButton btnRecursos;
    public javax.swing.JButton btnTablaPuntajes;
    public javax.swing.JButton btnTest;
    public javax.swing.JButton btnTraducir;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblESP;
    public javax.swing.JLabel lblQuechua;
    // End of variables declaration//GEN-END:variables
}
