/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author USER
 */
public class Registrarse extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public Registrarse() {
        initComponents();
        lblESP.setVisible(true);
        lblQuechua.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        txtContra = new javax.swing.JPasswordField();
        txtCorreo = new javax.swing.JTextField();
        btnRegistrarse = new javax.swing.JButton();
        btnTraducir = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        lblQuechua = new javax.swing.JLabel();
        lblESP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setToolTipText("");
        btnRegresar.setBorderPainted(false);
        btnRegresar.setContentAreaFilled(false);
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 40));

        txtContra.setBackground(new java.awt.Color(234, 234, 234));
        txtContra.setBorder(null);
        jPanel1.add(txtContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 420, 50));

        txtCorreo.setBackground(new java.awt.Color(234, 234, 234));
        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCorreo.setBorder(null);
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 440, 50));

        btnRegistrarse.setToolTipText("");
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setContentAreaFilled(false);
        jPanel1.add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 580, 320, 70));

        btnTraducir.setToolTipText("");
        btnTraducir.setBorderPainted(false);
        btnTraducir.setContentAreaFilled(false);
        jPanel1.add(btnTraducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 560, 90, 90));

        txtUsuario.setBackground(new java.awt.Color(234, 234, 234));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtUsuario.setBorder(null);
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 440, 50));

        lblQuechua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UIRegistroQUECHUA.jpg"))); // NOI18N
        jPanel1.add(lblQuechua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1090, 750));

        lblESP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UIRegistroESP.jpg"))); // NOI18N
        jPanel1.add(lblESP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrarse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnRegistrarse;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JButton btnTraducir;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblESP;
    public javax.swing.JLabel lblQuechua;
    public javax.swing.JPasswordField txtContra;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
