/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Ejercicios;

import Vista.MenuPrincipal;
import Vista.Informacion.I_Avanzado_Sufijo1;
import Vista.Felicidades;
import Vista.Lecciones_Avanzado;

/**
 *
 * @author USER
 */
public class Avanzado_PartesCuerpo2 extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
 public Avanzado_PartesCuerpo2() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpbProgreso = new javax.swing.JProgressBar();
        btnContinuar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        txtPregunta07 = new javax.swing.JTextField();
        txtPregunta08 = new javax.swing.JTextField();
        txtPregunta10 = new javax.swing.JTextField();
        txtPregunta12 = new javax.swing.JTextField();
        txtPregunta09 = new javax.swing.JTextField();
        txtPregunta11 = new javax.swing.JTextField();
        lblQuechua = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpbProgreso.setBackground(new java.awt.Color(175, 175, 175));
        jpbProgreso.setForeground(new java.awt.Color(255, 79, 79));
        jpbProgreso.setBorder(null);
        jPanel1.add(jpbProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 490, 30));

        btnContinuar.setToolTipText("");
        btnContinuar.setContentAreaFilled(false);
        btnContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 310, 60));

        btnRegresar.setToolTipText("");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 40));

        txtPregunta07.setBorder(null);
        jPanel1.add(txtPregunta07, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 210, 40));

        txtPregunta08.setBorder(null);
        jPanel1.add(txtPregunta08, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 210, 40));

        txtPregunta10.setBorder(null);
        jPanel1.add(txtPregunta10, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 210, 40));

        txtPregunta12.setBorder(null);
        jPanel1.add(txtPregunta12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, 210, 40));

        txtPregunta09.setBorder(null);
        jPanel1.add(txtPregunta09, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 210, 40));

        txtPregunta11.setBorder(null);
        jPanel1.add(txtPregunta11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 210, 40));

        lblQuechua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UIAvanzadoLecciones06ESP (1).png"))); // NOI18N
        jPanel1.add(lblQuechua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed

    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Avanzado_PartesCuerpo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Avanzado_PartesCuerpo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Avanzado_PartesCuerpo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Avanzado_PartesCuerpo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Avanzado_PartesCuerpo2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnContinuar;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JProgressBar jpbProgreso;
    public javax.swing.JLabel lblQuechua;
    public javax.swing.JTextField txtPregunta07;
    public javax.swing.JTextField txtPregunta08;
    public javax.swing.JTextField txtPregunta09;
    public javax.swing.JTextField txtPregunta10;
    public javax.swing.JTextField txtPregunta11;
    public javax.swing.JTextField txtPregunta12;
    // End of variables declaration//GEN-END:variables
}
