/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Ejercicios;

import Vista.Ejercicios.Avanzado_PartesCuerpo2;
import Vista.Lecciones_Avanzado;
import Vista.MenuPrincipal;

/**
 *
 * @author USER
 */
public class Avanzado_PartesCuerpo1 extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public Avanzado_PartesCuerpo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPregunta06 = new javax.swing.JTextField();
        txtPregunta01 = new javax.swing.JTextField();
        txtPregunta02 = new javax.swing.JTextField();
        txtPregunta03 = new javax.swing.JTextField();
        txtPregunta04 = new javax.swing.JTextField();
        txtPregunta05 = new javax.swing.JTextField();
        jpbProgreso = new javax.swing.JProgressBar();
        btnContinuar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblESP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPregunta06.setBorder(null);
        jPanel1.add(txtPregunta06, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 200, 40));

        txtPregunta01.setBorder(null);
        jPanel1.add(txtPregunta01, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 210, 40));

        txtPregunta02.setBorder(null);
        jPanel1.add(txtPregunta02, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 200, 40));

        txtPregunta03.setBorder(null);
        jPanel1.add(txtPregunta03, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 210, 40));

        txtPregunta04.setBorder(null);
        jPanel1.add(txtPregunta04, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 200, 40));

        txtPregunta05.setBorder(null);
        jPanel1.add(txtPregunta05, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 210, 40));

        jpbProgreso.setBackground(new java.awt.Color(175, 175, 175));
        jpbProgreso.setForeground(new java.awt.Color(255, 79, 79));
        jpbProgreso.setBorder(null);
        jPanel1.add(jpbProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 490, 20));

        btnContinuar.setToolTipText("");
        btnContinuar.setContentAreaFilled(false);
        jPanel1.add(btnContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, 310, 70));

        btnRegresar.setToolTipText("");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 40));

        lblESP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UIAvanzadoLecciones05ESP (1).png"))); // NOI18N
        jPanel1.add(lblESP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1100, 680));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Avanzado_PartesCuerpo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Avanzado_PartesCuerpo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Avanzado_PartesCuerpo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Avanzado_PartesCuerpo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Avanzado_PartesCuerpo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnContinuar;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JProgressBar jpbProgreso;
    public javax.swing.JLabel lblESP;
    public javax.swing.JTextField txtPregunta01;
    public javax.swing.JTextField txtPregunta02;
    public javax.swing.JTextField txtPregunta03;
    public javax.swing.JTextField txtPregunta04;
    public javax.swing.JTextField txtPregunta05;
    public javax.swing.JTextField txtPregunta06;
    // End of variables declaration//GEN-END:variables
}
