/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Recursos;

import Vista.MenuPrincipal;
import java.io.IOException;
import java.net.URISyntaxException;

/**
 *
 * @author USER
 */
public class RecursoMultimedia extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public RecursoMultimedia() {
        initComponents();
        lblESP.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        Palabras_Basicas_Quechua = new javax.swing.JButton();
        Quechua_AhoraMasFacil = new javax.swing.JButton();
        Aprende_Quechua_Facil = new javax.swing.JButton();
        lblESP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setToolTipText("");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 220, 40));

        Palabras_Basicas_Quechua.setToolTipText("");
        Palabras_Basicas_Quechua.setContentAreaFilled(false);
        Palabras_Basicas_Quechua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Palabras_Basicas_QuechuaActionPerformed(evt);
            }
        });
        jPanel1.add(Palabras_Basicas_Quechua, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 440, 40));

        Quechua_AhoraMasFacil.setToolTipText("");
        Quechua_AhoraMasFacil.setContentAreaFilled(false);
        Quechua_AhoraMasFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Quechua_AhoraMasFacilActionPerformed(evt);
            }
        });
        jPanel1.add(Quechua_AhoraMasFacil, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 550, 40));

        Aprende_Quechua_Facil.setToolTipText("");
        Aprende_Quechua_Facil.setContentAreaFilled(false);
        jPanel1.add(Aprende_Quechua_Facil, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 360, 40));

        lblESP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UIMultimedia (1).png"))); // NOI18N
        jPanel1.add(lblESP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
    
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void Palabras_Basicas_QuechuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Palabras_Basicas_QuechuaActionPerformed
        
    }//GEN-LAST:event_Palabras_Basicas_QuechuaActionPerformed

    private void Quechua_AhoraMasFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Quechua_AhoraMasFacilActionPerformed
       
    }//GEN-LAST:event_Quechua_AhoraMasFacilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecursoMultimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecursoMultimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecursoMultimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecursoMultimedia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecursoMultimedia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Aprende_Quechua_Facil;
    public javax.swing.JButton Palabras_Basicas_Quechua;
    public javax.swing.JButton Quechua_AhoraMasFacil;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblESP;
    // End of variables declaration//GEN-END:variables
}
