/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Recursos;

import Vista.MenuPrincipal;

/**
 *
 * @author USER
 */
public class RecursosQuechua extends javax.swing.JFrame {

    /**
     * Creates new form IniciarSesion
     */
    public RecursosQuechua() {
        initComponents();
        lblQuechua.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnAMultimedia = new javax.swing.JButton();
        btnLinkSuyan = new javax.swing.JButton();
        btnALinks = new javax.swing.JButton();
        btnLinkKultura = new javax.swing.JButton();
        lblQuechua = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setToolTipText("");
        btnRegresar.setContentAreaFilled(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 220, 40));

        btnAMultimedia.setToolTipText("");
        btnAMultimedia.setContentAreaFilled(false);
        btnAMultimedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAMultimediaActionPerformed(evt);
            }
        });
        jPanel1.add(btnAMultimedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 300, 280));

        btnLinkSuyan.setToolTipText("");
        btnLinkSuyan.setContentAreaFilled(false);
        btnLinkSuyan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinkSuyanActionPerformed(evt);
            }
        });
        jPanel1.add(btnLinkSuyan, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 510, 240, 80));

        btnALinks.setToolTipText("");
        btnALinks.setContentAreaFilled(false);
        btnALinks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALinksActionPerformed(evt);
            }
        });
        jPanel1.add(btnALinks, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 300, 260));

        btnLinkKultura.setToolTipText("");
        btnLinkKultura.setContentAreaFilled(false);
        btnLinkKultura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLinkKulturaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLinkKultura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 240, 80));

        lblQuechua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UIRecursosQuechua (1) (1).png"))); // NOI18N
        jPanel1.add(lblQuechua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        /*MenuPrincipal Menu = new MenuPrincipal();
        Menu.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnLinkSuyanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinkSuyanActionPerformed
     /*  RecursosLinks RL = new RecursosLinks();
        RL.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_btnLinkSuyanActionPerformed

    private void btnAMultimediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAMultimediaActionPerformed
      /* RecursoMultimedia RM = new RecursoMultimedia();
        RM.setVisible(true);
        this.dispose();*/
    }//GEN-LAST:event_btnAMultimediaActionPerformed

    private void btnALinksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALinksActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnALinksActionPerformed

    private void btnLinkKulturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLinkKulturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLinkKulturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecursosQuechua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecursosQuechua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecursosQuechua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecursosQuechua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecursosQuechua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnALinks;
    public javax.swing.JButton btnAMultimedia;
    public javax.swing.JButton btnLinkKultura;
    public javax.swing.JButton btnLinkSuyan;
    public javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lblQuechua;
    // End of variables declaration//GEN-END:variables
}
